### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by briatte** [kasperwelbers/semnet#1]
Hi,

Have you tried this package, which also implements the network backbone function?

https://github.com/alessandrobessi/disparityfilter

I need to update the package to kill a few bugs, but it should work fine for most cases.

Let me know :-)

**Comment by kasperwelbers** [comment]
Hi Briatte,

Yes, I have used it, in fact! :)

The reason for implementing our own version was that we had to use it on pretty large networks, and since we are not interested in parallel edges, we could use matrix algebra (my guess was that parallel edges, which cannot be represented in an adjacency matrix, is why you used for loops). 

I actually compared our implementation to yours for cross-checking (code attached), so please let me know if you expect your bug-fixes to affect the alpha calculation. 

Best,
Kasper

```r
# devtools::install_github('kasperwelbers/semnet')
# devtools::install_github('alessandrobessi/disparityfilter')
library(semnet) 
library(disparityfilter) 

######################## undirected networks. Gives the same results
set.seed(1)
g <- sample_pa(n = 500, m = 5, directed = FALSE)
E(g)$weight <- sample(1:25, ecount(g), replace = TRUE)

## same edges and alpha, though from/to can be switched (undirected network)
disparityfilter::backbone(g)
get.data.frame(semnet::getBackboneNetwork(g, delete.isolates = F)) 


######################## directed network. Gives the same results
set.seed(1)
g <- sample_pa(n = 500, m = 5, directed = TRUE)
E(g)$weight <- sample(1:25, ecount(g), replace = TRUE)

disparityfilter::backbone(g) 
get.data.frame(semnet::getBackboneNetwork(g, delete.isolates = F))


######################### directed network with parallel edges. Does not work with semnet
set.seed(1)
g <- sample_pa(n = 500, m = 5, directed = TRUE, algorithm = 'psumtree-multiple')
E(g)$weight <- sample(1:25, ecount(g), replace = TRUE)

disparityfilter::backbone(g) 
get.data.frame(semnet::getBackboneNetwork(g, delete.isolates = F))
```

**Comment by briatte** [comment]
Brilliant!

Very glad to hear that you have tried our code with @alessandrobessi.

The bugs in our code return null results in some cases, but do not affect the alpha.

I'll be giving a close look at your code soon to see if your matrix algebra can speed up our own code, which works fine but slowly.

Cheers, – ƒ

**Comment by kasperwelbers** [comment]
Just closing this issue

By the way, have you seen my issue on the disparityfilter github? It provides a vectorized solution for your disparity_filter function that doesn't require matching, which speeds things up massively. Do make sure to use the last solution posted, since FilipeamTeixeira noted a bug due to how the backbone function dealt with duplicates. 

Incidentally, the thread also turned out to discuss whether yours and our implementation are correct, which is eventually verified based on the same data as used by Serrano.

Cheers
